on: [push, pull_request]

jobs:
  alpine_aarch64_job:
    # The host should always be Linux
    runs-on: alpine-latest
    name: Build 
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: alpine-latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          run: |
             apk add --no-cache ghc cabal wget musl-dev zlib-dev zlib-static ncurses-dev ncurses-static
	     pwd
	     cabal update
	     cabal build --ghc-option=-optl=-static --ghc-option=-split-sections
	     cp -v ./dist-newstyle/build/aarch64-linux/ghc-*/elm-*/x/elm/build/elm/elm /usr/local/bin/elm